import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";


/// Components
import Header from "@/components/Header";


const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight : ["100", "200", "300", "400" , "500", "600", "700", "800"],
  display : "swap"
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jetbrainsMono.className} antialiased`}>
      <body
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
